apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_URI: "your-mongo-uri"
  JWT_SECRET: "your-jwt-secret"
  CLOUDINARY_CLOUD_NAME: "your-cloudinary-name"
  CLOUDINARY_API_KEY: "your-cloudinary-key"
  CLOUDINARY_API_SECRET: "your-cloudinary-secret"
  BREVO_API_KEY: "your-brevo-api-key"
  STRIPE_SECRET_KEY: "your-stripe-secret-key"
